apiVersion: v1
kind: Namespace
metadata:
  name: openwearables-production
  labels:
    name: openwearables-production
    environment: production
    managed-by: kubernetes
    app.kubernetes.io/name: openwearables
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: health-monitoring
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: openwearables-resource-quota
  namespace: openwearables-production
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: openwearables-limit-range
  namespace: openwearables-production
spec:
  limits:
  - default:
      cpu: "1"
      memory: 2Gi
    defaultRequest:
      cpu: 500m
      memory: 1Gi
    type: Container
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Container 