apiVersion: v1
kind: Service
metadata:
  name: openwearables-service
  namespace: openwearables-production
  labels:
    app: openwearables
    component: backend
    environment: production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-unhealthy-threshold: "3"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8000
    protocol: TCP
  selector:
    app: openwearables
    component: backend
  sessionAffinity: None
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: openwearables-service-internal
  namespace: openwearables-production
  labels:
    app: openwearables
    component: backend
    environment: production
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: openwearables
    component: backend
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: openwearables-celery-metrics
  namespace: openwearables-production
  labels:
    app: openwearables-celery
    component: worker
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9540"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9540
    targetPort: 9540
    protocol: TCP
  selector:
    app: openwearables-celery
    component: worker 